name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11'

    - name: Install dependencies
      run: npm install

    - name: Build and test
      run: npm run test

    - name: Configuration complete
      run: echo "Configuração do projeto foi feita com sucesso!"
